### ISSUE TITLE
[feat] SSH access

### ISSUE THREAD

**Issue by carlos22** [skylime/mi-core-kumquat#2]
Many modern PHP based software require you to use a commanline installer (e. g. composer based). For most users it would be sufficient to have a single admin user which can modify content of all files in `/var/www`. The most simple solution to this might be to enable the `www` user a login?

**Comment by drscream** [comment]
Would the use of the existing `admin` user with `sudo` rights an option to switch to `www` and run the required commands. I'm not sure if providing remote shell access to `www` user is a good idea anyway.

**Comment by carlos22** [comment]
I agree that i'm also not sure if it is a good idea to use the www user to login. But we at least need the option to change the file owner to www as otherwise the login is useless for deployment e.g. If you want to restrict more an user with only `www` sudo rights would also be ok.

**Comment by carlos22** [comment]
Any updates on this?

**Comment by drscream** [comment]
Feature has been implemented. A script `su-www` is able to switch to `www`
