### ISSUE TITLE
php5 opcache config

### ISSUE THREAD

**Issue by carlos22** [skylime/mi-core-kumquat#3]
Nextcloud tells the user that the opcode cache config is not good, these are the settings which are different in default php5 config and therefore kumquat:
```
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.memory_consumption=128
    opcache.revalidate_freq=1
```
Most of these values (all but opcache.revalidate_freq) are the new php7 defaults. See: https://secure.php.net/manual/de/opcache.configuration.php

We could set them in the php5 version also?!

**Comment by drscream** [comment]
Thanks for your report, this will be part of the next release!
