### ISSUE TITLE
How it works? 

### ISSUE THREAD

**Issue by marcheschi** [skylime/mi-core-kumquat#4]
Hi 
I tried to install the sunos zone and it is running , but I cannot find instruction on how to make it work, or what is the admin url, passwords, and so on.
Is there any documentation?
Thank you

Paolo

**Comment by drscream** [comment]
Hello Paolo,

sorry for the late reply, somehow I lost the GitHub notification.

Sadly we do not have any documentation which is additional available from the `README.md` in the repository. If you build or use the image provided by `mi-core-kumquat` the Kumquat web interface will be available via

https://fqdn.of.your.zone

So if you deploy an kumquat image via vmadm, the hostname will be used to generate an SSL certificate and provide this hostname as default for the management web interface.

Best regards,
Thomas

**Comment by marcheschi** [comment]
Thank you Thomas
I used : core-kumquat (20.1.2)
2725736b-4b37-4891-b1e2-cd1d56695e49
from skylime
And once I have it running I have this page:

Hello Friend,
i'm kumquat the small webhosting management

Nothing else.
Is it right?
Best regards
Paolo

**Comment by drscream** [comment]
Hallo Paolo,

that's already good. This is the default virtual host if you access for example only the IP address of your instance, or with an hostname which doesn't match the `hostname` provided with the `json` file. To access the management web interface you need to enter https://hostname - so using `https` and using the `hostname` which should be an FQDN provided to the JSON file as `hostname` variable.

Example:

```json
{
  "brand": "joyent",
  "image_uuid": "...",
  "autoboot": true,
  "alias": "kumquat.dev.example.com",
  "hostname": "kumquat.dev.example.com",
  "delegate_dataset": true,
  "dns_domain": "dev.example.com",
  "resolvers": [
    "8.8.8.8",
    "8.8.4.4"
  ]
...
```

With this example you should access https://kumquat.dev.example.com which should provide you with an management web interface. The username will be `admin`, and the password is automatically generated. To receive the password you should login with `ssh` or `zlogin` and use `mdata-get kumquat_admin_initial_pw`

**Comment by marcheschi** [comment]
Hi
I tried, now it is better:
DisallowedHost at /
Invalid HTTP_HOST header: 'kumquat.dev.mydomain.it'. You may need to add 'kumquat.dev.mydomain.it' to ALLOWED_HOSTS.
I tried to put in settings.py
ALLOWED_HOSTS = ['*']
But it is the same behaviour.
Paolo

**Comment by drscream** [comment]
Normally it should not be required to modify any configuration file manually, anyway a `svcadm restart gunicorn:kumquat` might be required before it's active.

To help you a bit better with your issue might you please share the following details (if not public feel free to drop me an email to tm AT core DOT io):

- `settings.py`
- `/opt/local/etc/httpd/vhosts/*` (all files but especially 00-* and 01-*)
- output of `hostname`

Be also sure everything run successfully and check `svcs` for services which are in maintenance state.

**Comment by marcheschi** [comment]
I tried 
svcadm restart gunicorn:kumquat 
But nothing changed
I sent you a mail
Thank you
Paolo

**Comment by marcheschi** [comment]
So I reinstalled the zone with Alias and hostname set to FQDN name.
And I added  ALLOWED_HOSTS = ['*'] to settings.py.
reboot
Now it shows the Login page !!
Thank you for your support
Paolo

**Comment by drscream** [comment]
It shouldn't be required to modify any configuration file manually. `ALLOWED_HOSTS` should be filled with the correct FQDN. If this isn't the case let me know. Anyway I would keep the issue open to provide better documentation for the future release.

**Comment by marcheschi** [comment]
This is not the case at least for me, I had to fill `ALLOWED_HOSTS ` it was empty [].
I took a look at the tool and I find it very useful thank you for your work.
Paolo

**Comment by drscream** [comment]
Hello Paolo,

thanks again for your feedback. A simple documentation and example is provided in the `docs` folder by now:

- [example-usage.md](https://github.com/skylime/mi-core-kumquat/blob/master/docs/example-usage.md)

I will close this issue, but feel free to contact us if you've any question or feature request.
